### PR TITLE
Feature/1202339773717002 Update FE to use a separate element tag on balance value

### PR DESCRIPTION
**Pull request by irediaes**
fix: moved balance and did values to a separate span tag for easy unit testing

### CODE REVIEW

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **marynashevchuk**
You can assign the PR to them by writing `/assign @marynashevchuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-fe).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/blob/dev/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by niazhussain** [comment]
:star: PR built and available in a preview **peaqnetwork-peaq-network-ev-charging-sim-fe-pr-16** [here](http://peaq-network-ev-charging-sim-fe-pr16.ci.peaq.network)

**Review by sfffaaa — APPROVED** [review]

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[sfffaaa](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/pull/16#pullrequestreview-984801044 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **marynashevchuk**
You can assign the PR to them by writing `/assign @marynashevchuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-fe).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/blob/dev/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[MarynaShevchuk](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/pull/16#issuecomment-1137233499 "Approved")*, *[sfffaaa](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/pull/16#pullrequestreview-984801044 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-fe).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/blob/dev/OWNERS)~~ [MarynaShevchuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[MarynaShevchuk](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/pull/16#issuecomment-1137233499 "Approved")*, *[sfffaaa](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/pull/16#pullrequestreview-984801044 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-fe).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-fe/blob/dev/OWNERS)~~ [MarynaShevchuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
